[build]
builder = "NIXPACKS"

[deploy]
startCommand = "gunicorn me_dashboard.wsgi --log-file -"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
