# Generated by Django 5.2.6 on 2025-09-21 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_add_created_by_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
    ]
